<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Laporan Inventory</title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size:12px; color:#333 }
        .title { text-align:center; margin-bottom:10px }
        .meta { margin-bottom:20px }
        .meta td { padding:3px 6px }
        table { width:100%; border-collapse:collapse; margin-bottom:18px }
        th, td { border:1px solid #ddd; padding:6px; }
        th { background:#4CAF50; color:#fff; font-weight:700 }
        .summary-table td { border:none; padding:4px }
        .small { font-size:11px; color:#666 }
    </style>
</head>
<body>
    <div class="title">
        <h2 style="margin:0">Laporan Inventory</h2>
        <div class="small">Generated: {{ now()->toDateTimeString() }}</div>
    </div>

    <table class="summary-table">
        <tr>
            <td><strong>Nilai Total Stok</strong></td>
            <td>Rp {{ number_format($nilai_total_stok,0,',','.') }}</td>
            <td><strong>Produksi Bulan Ini</strong></td>
            <td>{{ $produksi_bulan_ini }}</td>
            <td><strong>Alert Stok (&lt;10)</strong></td>
            <td>{{ $alert_stok }}</td>
        </tr>
    </table>

    <h4>Detail Stok Inventory</h4>
    <table>
        <thead>
            <tr>
                <th>Nama Bunga</th>
                <th>Kategori</th>
                <th>Stok Saat Ini</th>
                <th>Nilai Stok</th>
                <th>Status Kesegaran</th>
                <th>Status Stok</th>
            </tr>
        </thead>
        <tbody>
            @forelse($laporan_stok as $row)
            <tr>
                <td>{{ $row->name }}</td>
                <td>{{ $row->kategori }}</td>
                <td style="text-align:right">{{ $row->stock_now }}</td>
                <td style="text-align:right">Rp {{ number_format($row->nilai_stok,0,',','.') }}</td>
                <td>{{ $row->status_kesegaran ?? 'Segar' }}</td>
                <td>{{ $row->status_stok ?? ( $row->stock_now < 10 ? 'Menipis' : 'Aman') }}</td>
            </tr>
            @empty
            <tr><td colspan="5" style="text-align:center;color:#888">Tidak ada data</td></tr>
            @endforelse
        </tbody>
    </table>

    <h4>Penggunaan Bahan (Bulan ini)</h4>
    <table>
        <thead>
            <tr>
                <th>Nama Bunga</th>
                <th>Total Digunakan (tangkai)</th>
                <th>Persentase dari Stok Awal</th>
            </tr>
        </thead>
        <tbody>
            @forelse($penggunaan as $p)
            <tr>
                <td>{{ $p->flower_name }}</td>
                <td style="text-align:right">{{ $p->total_used }}</td>
                <td style="text-align:right">{{ isset($p->percent_display) ? $p->percent_display : '-' }}</td>
            </tr>
            @empty
            <tr><td colspan="3" style="text-align:center;color:#888">Tidak ada data penggunaan bulan ini</td></tr>
            @endforelse
        </tbody>
    </table>

    <h4>Peringatan & Rekomendasi</h4>
    <table>
        <thead>
            <tr>
                <th>Nama Bunga</th>
                <th>Stok Saat Ini</th>
                <th>Catatan Kadaluarsa</th>
            </tr>
        </thead>
        <tbody>
            @forelse($peringatan as $p)
            <tr>
                <td>{{ $p->name }}</td>
                <td style="text-align:right">{{ $p->stock_now }}</td>
                <td>{{ $p->expired_note ?? '-' }}</td>
            </tr>
            @empty
            <tr><td colspan="3" style="text-align:center;color:#888">Tidak ada peringatan</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="small">Generated by Project_SII</div>
</body>
</html>
